### PR TITLE
Initial work on parse push notifications

### PR DESCRIPTION
**Pull request by begedin**
- [Asana task: Add parse push notifications](https://app.asana.com/0/60127409159606/60649398425941)
# Description

This is initial work to add parse push notifications to the API. I have a PushNotification class which can be initialized to end to a channel or a specific user. The identifier used for a user and the channels in question are something we need to formally define.

I also have a failing spec which tries sending to a user and a channel. 
# NOTES
- ~~For some reason, vcr is being ignored for these specs. I'm not sure what's going on.~~
- The gem we use needs an APPLICATION_ID and an API_KEY. The API_KEY is the REST_API_KEY provided by Parse when creating a new app.

### CODE REVIEW

**Comment by begedin** [comment]
Since I'm done for the day, I'm fine with someone else taking this over until tomorrow, since I'm guessing it might be a bit higher priority than some of the other stuff.

**Comment by begedin** [comment]
I did as much as I could here without additional information.

The general idea is that the `ParseNotification` class wraps our Parse client and can send a message, either to a channel or to a user.

The `ParseNotifier` class, on the other hand is our "message factory" class. It defines a method for each type of message, which accepts certain parameters and then calls `ParseNotification.send` with the proper message, channel or username.

For now, since I don't know which notifications we will be sending, there is only a basic `ParseNotifier.ping` which sends the "Ping!" message to either a channel or a username.

## Channel messages

For channel messages to work, an iOS certificate needs to be set up. Before we do that, the spec that tests for sending a channel message will fail. Once it is set up, the VCR tape needs to be deleted, since it recorded a failed request.

## Questions
- What types of messages will we be sending?

**Comment by joshsmith** [comment]
Unless you explicitly add a VCR cassette, HTTP requests are now allowed. Is that the issue?

**Comment by begedin** [comment]
Sorry, the original description is out of date.

The issue was that using our standard way of assigning tapes (on the line where we define the spec name, using `vcr: { cassette_name: "foo" }` did not work.

However, wrapping the call itself into `VCR.use_cassette` did work.

**Comment by begedin** [comment]
@JoshSmith The only thing that's really missing now (in making it work in a basic way) is setting up a proper parse account (with an iOS certificate), so we can send messages to a channel and record valid request doing that.

Of course, we also need ot decide when we will be sending messages and to whom, and implement that. The code we have right now is just scaffolding, really.

**Comment by joshsmith** [comment]
I've added devices for a user with an endpoint for creating devices. This is hit any time a user authenticates and either updates or adds another device.

We need to:
- Write API specs for adding devices
- Write model specs for devices
- When someone passes their friends in points for the week, send a push notification to their friends that X has passed them, using all their enabled devices Parse tokens

**Comment by begedin** [comment]
An update: 
- [x] Write API specs for adding devices
  - @idelahoz  added one, which handles creation. I split it into two, to ensure it's either created or updated
- [x] Write model specs for devices
  - I added a basic model spec. Might need additional specs depending on code additions later.
- [x] When someone passes their friends in points for the week, send a push notification to their friends that X has passed them, using all their enabled devices Parse tokens

Also did:
- [x] Added device serializer and spec, corrected api specs so they expect the proper JSON API format

**Comment by joshsmith** [comment]
My guess is that we don't want to be hitting the Parse API, even with VCR. We should figure out a way to mock this out instead.

**Comment by begedin** [comment]
@JoshSmith The listed features are implemented and the specs work.

The current behavior is as follows
- When a user's score is changed, people that follow them will have their leaderboards updated.
- For each of those people, if the update affects their rank, they will get a notification to all of their devices about it. 
- The notification will be `"Your friend #{first_name} has beaten you."`.

We could easily modify the information sent with the message, but the functionality is there.

**Comment by begedin** [comment]
As for hitting the parse api in specs, the only place this is happening (with VCR) is while testing "ParseNotification.send". I would love to mock it instead, but it would have to be something along the lines of

```
expect(Parse::Push).to receive(:initialize).with(data: { message: <our message> })
expect_any_instance_of(Parse::Push).to receive(:save)
```

However, we'd have a problem with ensuring the query used to send the notification is sent correctly. I'm thinking having VCR in these two cases only is a good trade-off. We're just testing the API at a very basic level of sending to a device and to a channel. For everything else, we just check if these two thin wrapper methods are called.

**Pull request merged**
