### PR TITLE
Added inclusion of error code into EasyPost Error serialization

### PR DESCRIPTION
**Pull request by begedin**
- [Asana task: Transform Easypost error into a better error](https://app.asana.com/0/42698431045490/67550233260346)
# Description

An attempt to add more information into an EasyPost error by using the error code (which is something along the lines of a JSON API error ID).

However, I'm not completely sure this is something that fixes the specific issue described in the task. I could not produce an EasypostAPI error response which returns an error with ""Default address." as the message.

In order to add more detail to that one, I need more information to reproduce it.

### CODE REVIEW

**Comment by joshsmith** [comment]
The error is `EasyPost::Error: ADDRESS.VERIFY.FAILURE (400): Default address: The address you entered was found but more information is needed (such as an apartment, suite, or box number) to match to a specific address.`

**Comment by joshsmith** [comment]
It happens when the address doesn't have quite enough information. Example: `4166 Wilson Ave San Diego, CA 92104` is not specific enough, even though the address does exist.

**Comment by begedin** [comment]
@JoshSmith I added (and expanded) some specs, but in the case you described `error.detail` ends up equaling the full text of the error, not just "Default address:".

**Comment by begedin** [comment]
List of errors I was able to produce:

**When there's no street**

``` Ruby
{
  "message"=>"Insufficient address data provided. A street must be provided.", 
  "http_status"=>400,
  "http_body"=>"{\"error\":{\"code\":\"ADDRESS.VERIFY.FAILURE\",\"message\":\"Insufficient address data provided. A street must be provided.\",\"errors\":[]}}",
  "json_body"=>{:error=>{:code=>"ADDRESS.VERIFY.FAILURE", :message=>"Insufficient address data provided. A street must be provided.", :errors=>[]}},
  "param"=>nil,
  "code"=>"ADDRESS.VERIFY.FAILURE",
  "errors"=>[]
}
```

**When there's a street, but no city/state or zip**

``` Ruby
{
  "message"=>"Insufficient address data provided. A city and state or a zip must be provided.",
  "http_status"=>400,
  "http_body"=>"{\"error\":{\"code\":\"ADDRESS.VERIFY.FAILURE\",\"message\":\"Insufficient address data provided. A city and state or a zip must be provided.\",\"errors\":[]}}",
  "json_body"=>{:error=>{:code=>"ADDRESS.VERIFY.FAILURE", :message=>"Insufficient address data provided. A city and state or a zip must be provided.", :errors=>[]}},
  "param"=>nil,
  "code"=>"ADDRESS.VERIFY.FAILURE",
  "errors"=>[]
}
```

**When the address is not specific enough**

``` Ruby
{
  "message"=>"Default address: The address you entered was found but more information is needed (such as an apartment, suite, or box number) to match to a specific address.",
  "http_status"=>400,
  "http_body"=>
  "{\"error\":{\"code\":\"ADDRESS.VERIFY.FAILURE\",\"message\":\"Default address: The address you entered was found but more information is needed (such as an apartment, suite, or box number) to match to a specific address.\",\"errors\":[]}}",
  "json_body"=>
  {:error=>
    {:code=>"ADDRESS.VERIFY.FAILURE",
     :message=>"Default address: The address you entered was found but more information is needed (such as an apartment, suite, or box number) to match to a specific address.",
     :errors=>[]}},
  "param"=>nil,
  "code"=>"ADDRESS.VERIFY.FAILURE",
  "errors"=>[]
}
```

**Pull request merged**
